[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/home"
to = "/"
status = 300
force = true

[[redirects]]
from = "https://smt-calc.com"
to = "https://www.smt-calc.com"
status = 300
force = true

[[redirects]]
from = "https://smt-calc.netlify.app"
to = "https://www.smt-calc.com"
status = 300
force = true

